#!/bin/bash

source .env/bin/activate
PASSWORD=`cat ${HOME}/nap-email-password`
./emuf \
  --test mojo@whiteoaks.com \
  --smtphost mail.rs.whiteoaks.com \
  --user nap \
  --password "${PASSWORD}" \
  --mergefile merge.json
